tap "jandeobbleleer/oh-my-posh"
tap "FelixKratz/formulae"

brew "ack"
brew "adr-tools"
brew "openssl"
# brew "awscli"
brew "bash"
brew "colima"
brew "curl"
brew "kubectl"
brew "kubernetes-cli"
brew "direnv"
brew "docker", link: false
brew "git"
brew "git-absorb"
brew "gnu-sed"
brew "gnupg"
brew "jq"
# brew "imagemagick"
brew "libpq"
brew "openconnect"
brew "openssh"
brew "pinentry-mac"
# brew "postgresql"
# brew "redis", restart_service: true
brew "shellcheck"
# brew "stats"
brew "sqlfluff"
brew "tilt"
# brew "terraform"
brew "tfenv"
brew "tmux"
brew "unzip"
brew "vim"
brew "watch"
brew "wget"
brew "whois"
brew "yq"
brew "zsh"

# Kotlin
# brew "kotlin"
# brew "openjdk@17"

# Go
brew "go"
brew "goenv"
brew "golangci-lint"

# Python
brew "pyenv"

# Ruby
brew "rbenv"
brew "ruby-build"

# Node
brew "node"
brew "nodenv"

brew "borders"

# CLI timer
brew "caarlos0/tap/timer"
brew "terminal-notifier"

cask "visual-studio-code"
cask "slack"
cask "github"
cask "tuple"
cask "postman"
cask "ghostty"
cask "firefox"
# cask "wezterm"
cask "nikitabobko/tap/aerospace"
# cask "karabiner-elements"
